/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WidokPanel.java
 *
 * Created on 2011-05-04, 10:45:10
 */

package lift;



import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JSlider;
import javax.swing.JTextField;

/**
 *
 * @author Apapus
 */
public class WidokPanel extends javax.swing.JPanel {

    /** Creates new form WidokPanel */
    public WidokPanel() {
        initComponents();
        szyby();
    }
 int start = 1;
    ArrayList<JTextField> szyb1= new ArrayList<JTextField>();
    ArrayList<JTextField> szyb2= new ArrayList<JTextField>();
Pietro pieterko2;
int koniec = 20;
int ilosc = 1;


      double szybkosc = 1.0;



    public void szyby(){
        TextFieldIluPasazerow.setText("Ilu pasażerów?");
        TextFieldKoncowe.setText("Piętro końcowe");
        TextFieldPoczatkowe.setText("Piętro początkowe");
        ButtonDodaj.setText("Dodaj");
        ButtonStart.setText("Start");
        ButtonStop.setText("Stop");
        ButtonStop.setEnabled(false);
        ButtonWczytajListe.setText("Wczytaj listę");
        ButtonObejrzyj.setText("Obejrzyj listę pasażerów");
        RadioButtonAlgorytm1.setText("Algorytm 1 = 'Góra - Dół'");
        RadioButtonAlgorytm2.setText("Algorytm 2 = 'Gdzie bliżej'");
        RadioButtonAlgorytm3.setText("Algorytm 3 = 'Gdzie więcej'");
        RadioButtonDwieWindy.setText("Dwie windy");
        RadioButtonJednaWinda.setText("Jedna winda");
        LabelIluPasazerow.setText("Ilu pasażerów?");
        LabelKoncowe.setText("Piętro końcowe");
        LabelPoczatkowe.setText("Piętro początkowe");
        LabelPietro00.setText("00");
        ButtonWyczysc.setText("Wyczyść listę");

        szyb1.add(Pietro00);
        szyb1.add(Pietro1);
        szyb1.add(Pietro2);
        szyb1.add(Pietro3);
        szyb1.add(Pietro4);
        szyb1.add(Pietro5);
        szyb1.add(Pietro6);
        szyb1.add(Pietro7);
        szyb1.add(Pietro8);
        szyb1.add(Pietro9);
        szyb1.add(Pietro10);
        szyb1.add(Pietro11);
        szyb1.add(Pietro12);
        szyb1.add(Pietro13);
        szyb1.add(Pietro14);
        szyb1.add(Pietro15);
        szyb1.add(Pietro16);
        szyb1.add(Pietro17);
        szyb1.add(Pietro18);
        szyb1.add(Pietro19);
        szyb1.add(Pietro20);

        szyb2.add(Pietro200);
        szyb2.add(Pietro201);
        szyb2.add(Pietro202);
        szyb2.add(Pietro203);
        szyb2.add(Pietro204);
        szyb2.add(Pietro205);
        szyb2.add(Pietro206);
        szyb2.add(Pietro207);
        szyb2.add(Pietro208);
        szyb2.add(Pietro209);
        szyb2.add(Pietro210);
        szyb2.add(Pietro211);
        szyb2.add(Pietro212);
        szyb2.add(Pietro213);
        szyb2.add(Pietro214);
        szyb2.add(Pietro215);
        szyb2.add(Pietro216);
        szyb2.add(Pietro217);
        szyb2.add(Pietro218);
        szyb2.add(Pietro219);
        szyb2.add(Pietro220);

      koloruj();



    }
    public void koloruj(){
     
        for (JTextField field : szyb1)
        {
            field.setBackground(Color.white);
        }
        for (JTextField field : szyb2)
        {
            field.setBackground(Color.white);
        }

    }
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel22 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Pietro1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        Pietro220 = new javax.swing.JTextField();
        Pietro3 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        Pietro2 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Pietro219 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        Pietro217 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Pietro216 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        Pietro213 = new javax.swing.JTextField();
        Pietro212 = new javax.swing.JTextField();
        Pietro214 = new javax.swing.JTextField();
        Pietro218 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Pietro15 = new javax.swing.JTextField();
        Pietro14 = new javax.swing.JTextField();
        Pietro12 = new javax.swing.JTextField();
        Pietro9 = new javax.swing.JTextField();
        Pietro8 = new javax.swing.JTextField();
        Pietro11 = new javax.swing.JTextField();
        Pietro10 = new javax.swing.JTextField();
        Pietro6 = new javax.swing.JTextField();
        RadioButtonAlgorytm3 = new javax.swing.JRadioButton();
        RadioButtonAlgorytm2 = new javax.swing.JRadioButton();
        Pietro5 = new javax.swing.JTextField();
        SliderIloscPieter = new javax.swing.JSlider();
        SuwakSzybkosc = new javax.swing.JSlider();
        Pietro4 = new javax.swing.JTextField();
        RadioButtonDwieWindy = new javax.swing.JRadioButton();
        Pietro7 = new javax.swing.JTextField();
        RadioButtonJednaWinda = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        RadioButtonAlgorytm1 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Pietro17 = new javax.swing.JTextField();
        Pietro201 = new javax.swing.JTextField();
        Pietro19 = new javax.swing.JTextField();
        Pietro18 = new javax.swing.JTextField();
        Pietro20 = new javax.swing.JTextField();
        ButtonStart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaStanWind = new javax.swing.JTextArea();
        Pietro13 = new javax.swing.JTextField();
        Pietro16 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Pietro206 = new javax.swing.JTextField();
        Pietro210 = new javax.swing.JTextField();
        Pietro209 = new javax.swing.JTextField();
        Pietro215 = new javax.swing.JTextField();
        Pietro208 = new javax.swing.JTextField();
        Pietro211 = new javax.swing.JTextField();
        Pietro207 = new javax.swing.JTextField();
        Pietro204 = new javax.swing.JTextField();
        Pietro202 = new javax.swing.JTextField();
        Pietro203 = new javax.swing.JTextField();
        Pietro205 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ButtonStop = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        TextFieldIluPasazerow = new javax.swing.JTextField();
        TextFieldPoczatkowe = new javax.swing.JTextField();
        TextFieldKoncowe = new javax.swing.JTextField();
        LabelIluPasazerow = new javax.swing.JLabel();
        LabelPoczatkowe = new javax.swing.JLabel();
        LabelKoncowe = new javax.swing.JLabel();
        ButtonDodaj = new javax.swing.JButton();
        ButtonObejrzyj = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaPasazer = new javax.swing.JTextArea();
        ButtonWczytajListe = new javax.swing.JButton();
        ButtonWyczysc = new javax.swing.JButton();
        Pietro00 = new javax.swing.JTextField();
        Pietro200 = new javax.swing.JTextField();
        LabelPietro00 = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(lift.LiftApp.class).getContext().getResourceMap(WidokPanel.class);
        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N

        jLabel30.setText(resourceMap.getString("jLabel30.text")); // NOI18N
        jLabel30.setName("jLabel30"); // NOI18N

        Pietro1.setEditable(false);
        Pietro1.setName("Pietro1"); // NOI18N

        jLabel29.setText(resourceMap.getString("jLabel29.text")); // NOI18N
        jLabel29.setName("jLabel29"); // NOI18N

        Pietro220.setEditable(false);
        Pietro220.setName("Pietro220"); // NOI18N

        Pietro3.setEditable(false);
        Pietro3.setName("Pietro3"); // NOI18N

        jLabel31.setText(resourceMap.getString("jLabel31.text")); // NOI18N
        jLabel31.setName("jLabel31"); // NOI18N

        Pietro2.setEditable(false);
        Pietro2.setName("Pietro2"); // NOI18N

        jLabel26.setText(resourceMap.getString("jLabel26.text")); // NOI18N
        jLabel26.setName("jLabel26"); // NOI18N

        Pietro219.setEditable(false);
        Pietro219.setName("Pietro219"); // NOI18N

        jLabel28.setText(resourceMap.getString("jLabel28.text")); // NOI18N
        jLabel28.setName("jLabel28"); // NOI18N

        Pietro217.setEditable(false);
        Pietro217.setName("Pietro217"); // NOI18N

        jLabel27.setText(resourceMap.getString("jLabel27.text")); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N

        Pietro216.setEditable(false);
        Pietro216.setName("Pietro216"); // NOI18N

        jLabel33.setText(resourceMap.getString("jLabel33.text")); // NOI18N
        jLabel33.setName("jLabel33"); // NOI18N

        Pietro213.setEditable(false);
        Pietro213.setName("Pietro213"); // NOI18N

        Pietro212.setEditable(false);
        Pietro212.setName("Pietro212"); // NOI18N

        Pietro214.setEditable(false);
        Pietro214.setName("Pietro214"); // NOI18N

        Pietro218.setEditable(false);
        Pietro218.setName("Pietro218"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        Pietro15.setEditable(false);
        Pietro15.setName("Pietro15"); // NOI18N

        Pietro14.setEditable(false);
        Pietro14.setName("Pietro14"); // NOI18N

        Pietro12.setEditable(false);
        Pietro12.setName("Pietro12"); // NOI18N

        Pietro9.setEditable(false);
        Pietro9.setName("Pietro9"); // NOI18N

        Pietro8.setEditable(false);
        Pietro8.setName("Pietro8"); // NOI18N

        Pietro11.setEditable(false);
        Pietro11.setName("Pietro11"); // NOI18N

        Pietro10.setEditable(false);
        Pietro10.setName("Pietro10"); // NOI18N

        Pietro6.setEditable(false);
        Pietro6.setName("Pietro6"); // NOI18N

        buttonGroup2.add(RadioButtonAlgorytm3);
        RadioButtonAlgorytm3.setText(resourceMap.getString("RadioButtonAlgorytm3.text")); // NOI18N
        RadioButtonAlgorytm3.setName("RadioButtonAlgorytm3"); // NOI18N
        RadioButtonAlgorytm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonAlgorytm3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(RadioButtonAlgorytm2);
        RadioButtonAlgorytm2.setText(resourceMap.getString("RadioButtonAlgorytm2.text")); // NOI18N
        RadioButtonAlgorytm2.setName("RadioButtonAlgorytm2"); // NOI18N
        RadioButtonAlgorytm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonAlgorytm2ActionPerformed(evt);
            }
        });

        Pietro5.setEditable(false);
        Pietro5.setName("Pietro5"); // NOI18N

        SliderIloscPieter.setMaximum(20);
        SliderIloscPieter.setMinimum(5);
        SliderIloscPieter.setMinorTickSpacing(1);
        SliderIloscPieter.setPaintLabels(true);
        SliderIloscPieter.setPaintTicks(true);
        SliderIloscPieter.setSnapToTicks(true);
        SliderIloscPieter.setValue(6);
        SliderIloscPieter.setName("SliderIloscPieter"); // NOI18N
        SliderIloscPieter.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderIloscPieterStateChanged(evt);
            }
        });
        SliderIloscPieter.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SliderIloscPieterFocusGained(evt);
            }
        });

        SuwakSzybkosc.setMinimum(1);
        SuwakSzybkosc.setName("SuwakSzybkosc"); // NOI18N
        SuwakSzybkosc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SuwakSzybkoscStateChanged(evt);
            }
        });
        SuwakSzybkosc.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                SuwakSzybkoscPropertyChange(evt);
            }
        });

        Pietro4.setEditable(false);
        Pietro4.setName("Pietro4"); // NOI18N

        buttonGroup1.add(RadioButtonDwieWindy);
        RadioButtonDwieWindy.setSelected(true);
        RadioButtonDwieWindy.setText(resourceMap.getString("RadioButtonDwieWindy.text")); // NOI18N
        RadioButtonDwieWindy.setName("RadioButtonDwieWindy"); // NOI18N
        RadioButtonDwieWindy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonDwieWindyActionPerformed(evt);
            }
        });

        Pietro7.setEditable(false);
        Pietro7.setName("Pietro7"); // NOI18N

        buttonGroup1.add(RadioButtonJednaWinda);
        RadioButtonJednaWinda.setSelected(false);
        RadioButtonJednaWinda.setText(resourceMap.getString("RadioButtonJednaWinda.text")); // NOI18N
        RadioButtonJednaWinda.setName("RadioButtonJednaWinda"); // NOI18N
        RadioButtonJednaWinda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonJednaWindaActionPerformed(evt);
            }
        });

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        buttonGroup2.add(RadioButtonAlgorytm1);
        RadioButtonAlgorytm1.setSelected(true);
        RadioButtonAlgorytm1.setText(resourceMap.getString("RadioButtonAlgorytm1.text")); // NOI18N
        RadioButtonAlgorytm1.setName("RadioButtonAlgorytm1"); // NOI18N
        RadioButtonAlgorytm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButtonAlgorytm1ActionPerformed(evt);
            }
        });

        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N

        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N

        jLabel20.setText(resourceMap.getString("jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N

        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        Pietro17.setEditable(false);
        Pietro17.setName("Pietro17"); // NOI18N

        Pietro201.setEditable(false);
        Pietro201.setName("Pietro201"); // NOI18N

        Pietro19.setEditable(false);
        Pietro19.setName("Pietro19"); // NOI18N

        Pietro18.setEditable(false);
        Pietro18.setName("Pietro18"); // NOI18N

        Pietro20.setEditable(false);
        Pietro20.setName("Pietro20"); // NOI18N

        ButtonStart.setText(resourceMap.getString("ButtonStart.text")); // NOI18N
        ButtonStart.setName("ButtonStart"); // NOI18N
        ButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStartActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        TextAreaStanWind.setColumns(20);
        TextAreaStanWind.setEditable(false);
        TextAreaStanWind.setRows(5);
        TextAreaStanWind.setName("TextAreaStanWind"); // NOI18N
        jScrollPane1.setViewportView(TextAreaStanWind);

        Pietro13.setEditable(false);
        Pietro13.setName("Pietro13"); // NOI18N

        Pietro16.setEditable(false);
        Pietro16.setName("Pietro16"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        Pietro206.setEditable(false);
        Pietro206.setName("Pietro206"); // NOI18N

        Pietro210.setEditable(false);
        Pietro210.setName("Pietro210"); // NOI18N

        Pietro209.setEditable(false);
        Pietro209.setName("Pietro209"); // NOI18N

        Pietro215.setEditable(false);
        Pietro215.setName("Pietro215"); // NOI18N

        Pietro208.setEditable(false);
        Pietro208.setName("Pietro208"); // NOI18N

        Pietro211.setEditable(false);
        Pietro211.setName("Pietro211"); // NOI18N

        Pietro207.setEditable(false);
        Pietro207.setName("Pietro207"); // NOI18N

        Pietro204.setEditable(false);
        Pietro204.setName("Pietro204"); // NOI18N

        Pietro202.setEditable(false);
        Pietro202.setName("Pietro202"); // NOI18N

        Pietro203.setEditable(false);
        Pietro203.setName("Pietro203"); // NOI18N

        Pietro205.setEditable(false);
        Pietro205.setName("Pietro205"); // NOI18N

        jLabel23.setText(resourceMap.getString("jLabel23.text")); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N

        ButtonStop.setText(resourceMap.getString("ButtonStop.text")); // NOI18N
        ButtonStop.setName("ButtonStop"); // NOI18N
        ButtonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStopActionPerformed(evt);
            }
        });

        jInternalFrame1.setTitle(resourceMap.getString("jInternalFrame1.title")); // NOI18N
        jInternalFrame1.setName("jInternalFrame1"); // NOI18N
        jInternalFrame1.setVisible(true);

        TextFieldIluPasazerow.setText(resourceMap.getString("TextFieldIluPasazerow.text")); // NOI18N
        TextFieldIluPasazerow.setName("TextFieldIluPasazerow"); // NOI18N
        TextFieldIluPasazerow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIluPasazerowActionPerformed(evt);
            }
        });
        TextFieldIluPasazerow.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TextFieldIluPasazerowPropertyChange(evt);
            }
        });

        TextFieldPoczatkowe.setText(resourceMap.getString("TextFieldPoczatkowe.text")); // NOI18N
        TextFieldPoczatkowe.setName("TextFieldPoczatkowe"); // NOI18N
        TextFieldPoczatkowe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPoczatkoweActionPerformed(evt);
            }
        });
        TextFieldPoczatkowe.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TextFieldPoczatkowePropertyChange(evt);
            }
        });

        TextFieldKoncowe.setText(resourceMap.getString("TextFieldKoncowe.text")); // NOI18N
        TextFieldKoncowe.setName("TextFieldKoncowe"); // NOI18N
        TextFieldKoncowe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldKoncoweActionPerformed(evt);
            }
        });
        TextFieldKoncowe.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TextFieldKoncowePropertyChange(evt);
            }
        });

        LabelIluPasazerow.setText(resourceMap.getString("LabelIluPasazerow.text")); // NOI18N
        LabelIluPasazerow.setName("LabelIluPasazerow"); // NOI18N

        LabelPoczatkowe.setText(resourceMap.getString("LabelPoczatkowe.text")); // NOI18N
        LabelPoczatkowe.setName("LabelPoczatkowe"); // NOI18N

        LabelKoncowe.setText(resourceMap.getString("LabelKoncowe.text")); // NOI18N
        LabelKoncowe.setName("LabelKoncowe"); // NOI18N

        ButtonDodaj.setText(resourceMap.getString("ButtonDodaj.text")); // NOI18N
        ButtonDodaj.setName("ButtonDodaj"); // NOI18N
        ButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDodajActionPerformed(evt);
            }
        });

        ButtonObejrzyj.setText(resourceMap.getString("ButtonObejrzyj.text")); // NOI18N
        ButtonObejrzyj.setName("ButtonObejrzyj"); // NOI18N
        ButtonObejrzyj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonObejrzyjActionPerformed(evt);
            }
        });

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        TextAreaPasazer.setColumns(20);
        TextAreaPasazer.setRows(5);
        TextAreaPasazer.setName("TextAreaPasazer"); // NOI18N
        jScrollPane2.setViewportView(TextAreaPasazer);

        ButtonWczytajListe.setText(resourceMap.getString("ButtonWczytajListe.text")); // NOI18N
        ButtonWczytajListe.setName("ButtonWczytajListe"); // NOI18N
        ButtonWczytajListe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonWczytajListeActionPerformed(evt);
            }
        });

        ButtonWyczysc.setText(resourceMap.getString("ButtonWyczysc.text")); // NOI18N
        ButtonWyczysc.setName("ButtonWyczysc"); // NOI18N
        ButtonWyczysc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonWyczyscActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TextFieldKoncowe, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldPoczatkowe, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldIluPasazerow, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelIluPasazerow)
                            .addComponent(LabelPoczatkowe)
                            .addComponent(LabelKoncowe)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(ButtonDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonObejrzyj, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(ButtonWczytajListe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonWyczysc))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldIluPasazerow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelIluPasazerow))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldPoczatkowe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPoczatkowe))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldKoncowe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelKoncowe))
                .addGap(26, 26, 26)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonObejrzyj, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonWyczysc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonWczytajListe))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jInternalFrame1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ButtonDodaj, ButtonObejrzyj, ButtonWczytajListe});

        Pietro00.setEditable(false);
        Pietro00.setName("Pietro00"); // NOI18N

        Pietro200.setEditable(false);
        Pietro200.setName("Pietro200"); // NOI18N

        LabelPietro00.setText(resourceMap.getString("LabelPietro00.text")); // NOI18N
        LabelPietro00.setName("LabelPietro00"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel27)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20)
                                            .addComponent(LabelPietro00))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Pietro1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                            .addComponent(Pietro2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                            .addComponent(Pietro3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                            .addComponent(Pietro4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                            .addComponent(Pietro5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                            .addComponent(Pietro15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                            .addComponent(Pietro16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                            .addComponent(Pietro17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                            .addComponent(Pietro19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                            .addComponent(Pietro18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                            .addComponent(Pietro14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                            .addComponent(Pietro13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                            .addComponent(Pietro12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                            .addComponent(Pietro11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                            .addComponent(Pietro10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                            .addComponent(Pietro9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                            .addComponent(Pietro8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                            .addComponent(Pietro7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                            .addComponent(Pietro6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                            .addComponent(Pietro20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                            .addComponent(Pietro00, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Pietro217, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(Pietro216, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(Pietro219, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(Pietro218, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(Pietro214, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(Pietro212, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(Pietro213, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(Pietro215, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(Pietro209, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(Pietro211, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(Pietro208, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(Pietro210, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(Pietro220, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(Pietro207, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(Pietro206, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(Pietro205, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(Pietro204, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(Pietro203, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(Pietro202, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(Pietro201, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(Pietro200, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel28)))))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RadioButtonJednaWinda)
                                    .addComponent(RadioButtonDwieWindy)
                                    .addComponent(SliderIloscPieter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)
                                    .addComponent(RadioButtonAlgorytm3)
                                    .addComponent(RadioButtonAlgorytm1)
                                    .addComponent(RadioButtonAlgorytm2)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel22)
                                    .addComponent(SuwakSzybkosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ButtonStart)
                                        .addGap(46, 46, 46)
                                        .addComponent(ButtonStop)))
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(427, 427, 427)
                    .addComponent(jLabel31)
                    .addGap(339, 339, 339)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Pietro1, Pietro10, Pietro11, Pietro12, Pietro13, Pietro14, Pietro15, Pietro16, Pietro17, Pietro18, Pietro19, Pietro2, Pietro20, Pietro200, Pietro201, Pietro202, Pietro203, Pietro204, Pietro205, Pietro206, Pietro207, Pietro208, Pietro209, Pietro210, Pietro211, Pietro212, Pietro213, Pietro214, Pietro215, Pietro216, Pietro217, Pietro218, Pietro219, Pietro220, Pietro3, Pietro4, Pietro5, Pietro6, Pietro7, Pietro8, Pietro9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel29))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Pietro20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Pietro19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Pietro18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Pietro17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Pietro16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Pietro15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Pietro14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Pietro13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Pietro12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Pietro11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Pietro10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Pietro9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Pietro8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Pietro7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14)
                                            .addComponent(Pietro207, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Pietro6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15)
                                            .addComponent(Pietro206, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Pietro5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16)
                                            .addComponent(Pietro205, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(Pietro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel17))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(Pietro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel18))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(Pietro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel19))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(Pietro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(Pietro00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(LabelPietro00)))
                                                    .addComponent(jLabel20)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Pietro204, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Pietro203, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Pietro202, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Pietro201, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Pietro200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel11)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Pietro220, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pietro219, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pietro218, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Pietro217, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Pietro216, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Pietro215, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Pietro214, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Pietro213, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Pietro212, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RadioButtonAlgorytm1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RadioButtonAlgorytm2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RadioButtonAlgorytm3)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Pietro211, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Pietro210, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Pietro209, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Pietro208, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SuwakSzybkosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ButtonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SliderIloscPieter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioButtonJednaWinda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RadioButtonDwieWindy))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(27, 27, 27))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(709, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ButtonStart, ButtonStop});

    }// </editor-fold>//GEN-END:initComponents

    private void RadioButtonAlgorytm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonAlgorytm3ActionPerformed
        Zmienne.uzywanyAlgorytm = new MyAlgorytm3();
}//GEN-LAST:event_RadioButtonAlgorytm3ActionPerformed

    private void RadioButtonAlgorytm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonAlgorytm2ActionPerformed
        Zmienne.uzywanyAlgorytm = new MyAlgorytm2();
}//GEN-LAST:event_RadioButtonAlgorytm2ActionPerformed

    private void SliderIloscPieterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderIloscPieterStateChanged
        JSlider source = (JSlider)evt.getSource();
        if (!source.getValueIsAdjusting()){
            lift.Zmienne.iloscPieter=source.getValue();

            for (JTextField pieterko : szyb1) {
                pieterko.setVisible(true);
            }
            if (Zmienne.iloscWind == 2)
                for (JTextField pieterko : szyb2) {
                    pieterko.setVisible(true);
                }

                for (int i = 20; i>(source.getValue()); i--) {
                    szyb1.get(i).setVisible(false);
                    szyb2.get(i).setVisible(false);
                }
        }
}//GEN-LAST:event_SliderIloscPieterStateChanged
        int czas;
    private void SuwakSzybkoscPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_SuwakSzybkoscPropertyChange
       // czas = 20 * SuwakSzybkosc.getValue();
}//GEN-LAST:event_SuwakSzybkoscPropertyChange

    private void RadioButtonDwieWindyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonDwieWindyActionPerformed
        Zmienne.iloscWind = 2;
        for (JTextField pieterko : szyb2) {
            pieterko.setVisible(true);
        }
}//GEN-LAST:event_RadioButtonDwieWindyActionPerformed

    private void RadioButtonJednaWindaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonJednaWindaActionPerformed
        Zmienne.iloscWind = 1;
        hideSecondShaft();
    }//GEN-LAST:event_RadioButtonJednaWindaActionPerformed

    private void hideSecondShaft() {
        for (JTextField pieterko : szyb2) {
            pieterko.setVisible(false);
        }
    }

    private void RadioButtonAlgorytm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButtonAlgorytm1ActionPerformed
        Zmienne.uzywanyAlgorytm = new MyAlgorytm1();
}//GEN-LAST:event_RadioButtonAlgorytm1ActionPerformed
    private javax.swing.Timer timer = null;
    private void ButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStartActionPerformed
        
        Pietro pom;
        Zmienne.lista.lista.clear();
        koloruj();
        timer =new javax.swing.Timer(czas,new ActionListener()
        {
          int i =0;         
          int j =0;
          int k =0;
          int pierwszeaktualne=0;
          int pierwszepoprzednie=0;
          int drugieaktualne=0;
          int drugiepoprzednie=0;
          String pierwsze="";
          String drugie="";
          String calosc="";
          String wejsciejeden="";
          String wejsciedwa="";
          String wyjsciejeden="";
          String wyjsciedwa="";
          Pietro pom;
          Boolean zmianajedenplus;
          Boolean zmianadwaplus;
          Boolean zmianajedenminus;
          Boolean zmianadwaminus;
          Boolean zmianajedenoba;
          Boolean zmianadwaoba;

            public void actionPerformed(ActionEvent evt)
            {
                pierwsze="";
                drugie="";
                wejsciejeden="";
                wejsciedwa="";
                wyjsciejeden="";
                wyjsciedwa="";
                zmianajedenplus = false;
                zmianadwaplus = false;
                zmianadwaminus = false;
                zmianajedenminus = false;
                zmianajedenoba = false;
                zmianadwaoba = false;
                if (k<Zmienne.listapieterjeden.size()){
                    pierwszepoprzednie = pierwszeaktualne;
                    pierwszeaktualne = Zmienne.listapieterjeden.get(k).numerPietra;
                    if (Zmienne.listapieterjeden.get(k).iloscWchodzacych!=0)
                    {
                        zmianajedenplus = true;
                        wejsciejeden=String.valueOf(Zmienne.listapieterjeden.get(k).iloscWchodzacych);
                    }
                    if (Zmienne.listapieterjeden.get(k).iloscWychodzacych!=0)
                    {
                        if (zmianajedenplus)
                            zmianajedenoba = true;
                        zmianajedenminus = true;
                        wyjsciejeden=String.valueOf(Zmienne.listapieterjeden.get(k).iloscWychodzacych);
                    }
                    szyb1.get(pierwszeaktualne).setBackground(Color.red);
                    if (zmianajedenoba)
                        szyb1.get(pierwszeaktualne).setText("+" + wejsciejeden + " -" +wyjsciejeden);
                    if (zmianajedenplus)
                        szyb1.get(pierwszeaktualne).setText("+" + wejsciejeden);
                    if (zmianajedenminus)
                        szyb1.get(pierwszeaktualne).setText("-" + wyjsciejeden);
                    if (pierwszeaktualne!=pierwszepoprzednie)
                        szyb1.get(pierwszepoprzednie).setBackground(Color.white); 
                    szyb1.get(pierwszepoprzednie).setText("");
                    pierwsze = Zmienne.listapieterjeden.get(pierwszeaktualne).toString();
              
                }
                if (j<Zmienne.listapieterdwa.size()){
                    drugiepoprzednie = drugieaktualne;
                    drugieaktualne = Zmienne.listapieterdwa.get(j).numerPietra;

                    if (Zmienne.listapieterdwa.get(j).iloscWchodzacych!=0)
                    {
                        zmianadwaplus = true;
                        wejsciedwa=String.valueOf(Zmienne.listapieterdwa.get(j).iloscWchodzacych);
                    }
                    if (Zmienne.listapieterdwa.get(j).iloscWychodzacych!=0)
                    {
                        if (zmianadwaplus)
                            zmianadwaoba = true;
                        zmianadwaminus = true;
                        wyjsciedwa=String.valueOf(Zmienne.listapieterdwa.get(j).iloscWychodzacych);
                    }
                    szyb2.get(drugieaktualne).setBackground(Color.red);
                    if (zmianadwaoba)
                        szyb2.get(drugieaktualne).setText("+" + wejsciedwa + " -" +wyjsciedwa);
                    if (zmianadwaplus)
                        szyb2.get(drugieaktualne).setText("+" + wejsciedwa);
                    if (zmianadwaminus)
                        szyb2.get(drugieaktualne).setText("-" + wyjsciedwa);

                    
                   
                    if (drugieaktualne != drugiepoprzednie)
                    szyb2.get(drugiepoprzednie).setBackground(Color.white);
                    szyb2.get(drugiepoprzednie).setText("");
                    drugie = Zmienne.listapieterdwa.get(j).toString();
                }
                calosc +=pierwsze;
                calosc += drugie;
                TextAreaStanWind.setText(calosc);
                j++;
                k++;
                i++;
                if (i == Zmienne.lista.lista.size())
                    timer.stop();
            }
        });
        if (Zmienne.listaPasazerow.isEmpty())
            TextAreaStanWind.setText("Nie podano pasażerów");
        else
        {
            LiftApp.startuj();


        for (int j = 0; j<Zmienne.lista.lista.size();j++)
            if ((pom = Zmienne.lista.lista.get(j)).numerWindy==1)
                Zmienne.listapieterjeden.add(pom);
                else Zmienne.listapieterdwa.add(pom);

        timer.start();
        ButtonStop.setEnabled(true);
        }
    }//GEN-LAST:event_ButtonStartActionPerformed

    private void ButtonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStopActionPerformed
        if (timer.isRunning())
        {
        timer.stop();
        ButtonStop.setEnabled(false);
        }
    }//GEN-LAST:event_ButtonStopActionPerformed

    private void TextFieldIluPasazerowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIluPasazerowActionPerformed
        try{
        pomocnicza1 = TextFieldIluPasazerow.getText();
        nowy_ile = Integer.parseInt(pomocnicza1);
        if (nowy_ile < 0) nowy_ile = Math.abs(nowy_ile);
        System.out.println("Nowy ile = " +nowy_ile);
        } catch (Exception e){
            nowy_ile = 1;
        }    }//GEN-LAST:event_TextFieldIluPasazerowActionPerformed

    private void TextFieldPoczatkoweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPoczatkoweActionPerformed
        try{
        pomocnicza2 = TextFieldPoczatkowe.getText();
        nowy_pocz = Integer.parseInt(pomocnicza2);
        if (nowy_pocz < 0) nowy_pocz = 0;
        else if (nowy_pocz > 20) nowy_pocz = 20;
        System.out.println("Nowy pocz = " +nowy_pocz);
        } catch (Exception e) {
            System.out.println("W wyjatku " + pomocnicza2);
            nowy_pocz = 1;
        }    }//GEN-LAST:event_TextFieldPoczatkoweActionPerformed
    int nowy_ile = 1;
    private void TextFieldIluPasazerowPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TextFieldIluPasazerowPropertyChange
        try{
        pomocnicza1 = TextFieldIluPasazerow.getText();
        nowy_ile = Integer.parseInt(pomocnicza1);
        if (nowy_ile < 0) nowy_ile = Math.abs(nowy_ile);
        System.out.println("Nowy ile = " +nowy_ile);
        } catch (Exception e){
            nowy_ile = 1;
        }
    }//GEN-LAST:event_TextFieldIluPasazerowPropertyChange
    int nowy_pocz = 1;
    private void TextFieldPoczatkowePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TextFieldPoczatkowePropertyChange
        try{
        pomocnicza2 = TextFieldPoczatkowe.getText();
        nowy_pocz = Integer.parseInt(pomocnicza2);
        if (nowy_pocz < 0) nowy_pocz = 0;
        else if (nowy_pocz > 20) nowy_pocz = 20;
        System.out.println("Nowy pocz = " +nowy_pocz);
        } catch (Exception e) {

            nowy_pocz = 1;
        }
    }//GEN-LAST:event_TextFieldPoczatkowePropertyChange
    int nowy_kon = Zmienne.iloscPieter;
    String pomocnicza1;
    String pomocnicza2;
    String pomocnicza3;
    private void TextFieldKoncowePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TextFieldKoncowePropertyChange
        try{
            pomocnicza1 = TextFieldKoncowe.getText();
        nowy_kon = Integer.parseInt(pomocnicza1);
        if (nowy_kon < 0) nowy_kon = 0;
        else if (nowy_kon > 20) nowy_kon = 20;
        System.out.println("Change Nowy kon = " +nowy_kon);
        } catch (Exception e){
            nowy_kon = Zmienne.iloscPieter;
        }
    }//GEN-LAST:event_TextFieldKoncowePropertyChange

    private void SliderIloscPieterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SliderIloscPieterFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_SliderIloscPieterFocusGained

    private void ButtonObejrzyjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonObejrzyjActionPerformed
        String napis="";
        String napispojedynczy="";
        if (Zmienne.listaPasazerow.isEmpty())
            napis="Nie ma wczytanych pasażerów";
        else
        for (Pasazer pasazer  : Zmienne.listaPasazerow) {
            napispojedynczy = pasazer.iloscOut() + " pasazerów z pietra " + pasazer.startOut() + " na pietro " + pasazer.celOut();
            napis+=napispojedynczy+"\n";
        }

        TextAreaPasazer.setText(napis);
    }//GEN-LAST:event_ButtonObejrzyjActionPerformed

    private void ButtonWczytajListeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonWczytajListeActionPerformed
        Zmienne.listaPasazerow.add(new Pasazer(1, 3, 5));
        Zmienne.listaPasazerow.add(new Pasazer(2, 11, 5));
        Zmienne.listaPasazerow.add(new Pasazer(3, 18, 11));
        Zmienne.listaPasazerow.add(new Pasazer(4, 2, 10));
        Zmienne.listaPasazerow.add(new Pasazer(5, 8, 4));
        Zmienne.listaPasazerow.add(new Pasazer(6, 12, 16));
        Zmienne.listaPasazerow.add(new Pasazer(7, 15, 10));
    }//GEN-LAST:event_ButtonWczytajListeActionPerformed

    private void ButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDodajActionPerformed
        TextFieldPoczatkoweActionPerformed(null);
        TextFieldIluPasazerowActionPerformed(null);
        TextFieldKoncoweActionPerformed(null);

        Zmienne.listaPasazerow.add(new Pasazer(nowy_ile, nowy_pocz, nowy_kon));
    }//GEN-LAST:event_ButtonDodajActionPerformed

    private void TextFieldKoncoweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldKoncoweActionPerformed
        try{
            pomocnicza3 = TextFieldKoncowe.getText();
        nowy_kon = Integer.parseInt(pomocnicza3);
        if (nowy_kon < 0) nowy_kon = 0;
        else if (nowy_kon > 20) nowy_kon = 20;
        System.out.println("Nowy kon = " +nowy_kon);
        } catch (Exception e){
            nowy_kon = Zmienne.iloscPieter;
        }
    }//GEN-LAST:event_TextFieldKoncoweActionPerformed

    private void ButtonWyczyscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonWyczyscActionPerformed
        Zmienne.listaPasazerow.clear();
    }//GEN-LAST:event_ButtonWyczyscActionPerformed

    private void SuwakSzybkoscStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SuwakSzybkoscStateChanged
        czas = 2000 / SuwakSzybkosc.getValue();
        System.out.println(SuwakSzybkosc.getValue());
    }//GEN-LAST:event_SuwakSzybkoscStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDodaj;
    private javax.swing.JButton ButtonObejrzyj;
    private javax.swing.JButton ButtonStart;
    private javax.swing.JButton ButtonStop;
    private javax.swing.JButton ButtonWczytajListe;
    private javax.swing.JButton ButtonWyczysc;
    private javax.swing.JLabel LabelIluPasazerow;
    private javax.swing.JLabel LabelKoncowe;
    private javax.swing.JLabel LabelPietro00;
    private javax.swing.JLabel LabelPoczatkowe;
    private javax.swing.JTextField Pietro00;
    private javax.swing.JTextField Pietro1;
    private javax.swing.JTextField Pietro10;
    private javax.swing.JTextField Pietro11;
    private javax.swing.JTextField Pietro12;
    private javax.swing.JTextField Pietro13;
    private javax.swing.JTextField Pietro14;
    private javax.swing.JTextField Pietro15;
    private javax.swing.JTextField Pietro16;
    private javax.swing.JTextField Pietro17;
    private javax.swing.JTextField Pietro18;
    private javax.swing.JTextField Pietro19;
    private javax.swing.JTextField Pietro2;
    private javax.swing.JTextField Pietro20;
    private javax.swing.JTextField Pietro200;
    private javax.swing.JTextField Pietro201;
    private javax.swing.JTextField Pietro202;
    private javax.swing.JTextField Pietro203;
    private javax.swing.JTextField Pietro204;
    private javax.swing.JTextField Pietro205;
    private javax.swing.JTextField Pietro206;
    private javax.swing.JTextField Pietro207;
    private javax.swing.JTextField Pietro208;
    private javax.swing.JTextField Pietro209;
    private javax.swing.JTextField Pietro210;
    private javax.swing.JTextField Pietro211;
    private javax.swing.JTextField Pietro212;
    private javax.swing.JTextField Pietro213;
    private javax.swing.JTextField Pietro214;
    private javax.swing.JTextField Pietro215;
    private javax.swing.JTextField Pietro216;
    private javax.swing.JTextField Pietro217;
    private javax.swing.JTextField Pietro218;
    private javax.swing.JTextField Pietro219;
    private javax.swing.JTextField Pietro220;
    private javax.swing.JTextField Pietro3;
    private javax.swing.JTextField Pietro4;
    private javax.swing.JTextField Pietro5;
    private javax.swing.JTextField Pietro6;
    private javax.swing.JTextField Pietro7;
    private javax.swing.JTextField Pietro8;
    private javax.swing.JTextField Pietro9;
    private javax.swing.JRadioButton RadioButtonAlgorytm1;
    private javax.swing.JRadioButton RadioButtonAlgorytm2;
    private javax.swing.JRadioButton RadioButtonAlgorytm3;
    private javax.swing.JRadioButton RadioButtonDwieWindy;
    private javax.swing.JRadioButton RadioButtonJednaWinda;
    private javax.swing.JSlider SliderIloscPieter;
    private javax.swing.JSlider SuwakSzybkosc;
    private javax.swing.JTextArea TextAreaPasazer;
    static javax.swing.JTextArea TextAreaStanWind;
    private javax.swing.JTextField TextFieldIluPasazerow;
    private javax.swing.JTextField TextFieldKoncowe;
    private javax.swing.JTextField TextFieldPoczatkowe;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
